# Database configuration is fully configurable via environment variables.
# Sensible defaults are provided for local development and test.

default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER", "postgresql") %>
  encoding: <%= ENV.fetch("DB_ENCODING", "unicode") %>
  pool: <%= Integer(ENV.fetch("DB_POOL", ENV.fetch("RAILS_MAX_THREADS", 5))) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= Integer(ENV.fetch("DB_PORT", 5432)) %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  # Prefer DATABASE_URL_DEVELOPMENT, then DATABASE_URL, else discrete fields above
  url: <%= ENV["DATABASE_URL_DEVELOPMENT"] || ENV["DATABASE_URL"] %>
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "linksports_server_development") %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"] || ENV["DATABASE_URL"] %>
  database: <%= ENV.fetch("DB_NAME_TEST", "linksports_server_test") %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL_PRODUCTION"] || ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("DB_NAME_PRODUCTION", "linksports_server_production") %>
    username: <%= ENV["DB_USERNAME_PRODUCTION"] || ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD_PRODUCTION"] || ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST_PRODUCTION"] || ENV["DB_HOST"] %>
    port: <%= Integer((ENV["DB_PORT_PRODUCTION"] || ENV["DB_PORT"] || 5432).to_i) %>
